spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/demo-first
          jwk-set-uri: http://localhost:9090/realms/demo-first/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      resource-id: demo
      principle-attribute: preferred_username

keycloak:
  realm: demo-first
  endpoint: http://localhost:9090
  application:
    client-id: demo-login
    client-secret: oDUOFuvUskXQMS6RA0VSccdIOQ5eQYPW